//%attributes = {"invisible":true}
// ----------------------------------------------------
// Project Method: Compiler_OT_Host_CheckVariable

// Compiler method for OT Host CheckVariable

// This method was automatically generated by the
//   nativeObjectTools component on Apr 5, 2026

// ----------------------------------------------------

C_TEXT:C284(OT Host CheckVariable; $0; $1; $2)
