//%attributes = {"lang":"en","invisible":true}
// ----------------------------------------------------
// Project Method: Compiler_OTHostGetPointer

// Compiler method for the OT Host GetPointer method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by the nativeObjectTools component on Apr 13, 2026

// ----------------------------------------------------

C_TEXT:C284(OT Host GetPointer; $1)
C_POINTER:C301(OT Host GetPointer; $0)
