name: Set wombat as default branch and delete main

on:
  workflow_dispatch:

jobs:
  switch-default-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      administration: write
    steps:
      - name: Change default branch to wombat
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method PATCH /repos/${{ github.repository }} \
            -f default_branch=wombat

      - name: Delete main branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method DELETE /repos/${{ github.repository }}/git/refs/heads/main
